### ISSUE TITLE
listen for Theme change

### ISSUE THREAD

**Issue by ptfw** [saadeghi/theme-change#11]
I am using a charting library that manages its own style attributes through setting hex color values (css not an option).
the only way to update those style attributes is to send in new options setting in a javascript function. 
I could probably respond to the theme change using MutationObserver to observe the change to the data-theme attribute on the HTML element. But was wondering if you knew of a better way? 
or if you would consider emitting (dispatchEvent) a CustomEvent  that we could listen for when the theme is toggled (changed)?

**Comment by saadeghi** [comment]
I think you should go with MutationObserver because:
1. I prefer to keep this script as as simple as possible to do just one job.
2. This is a rare feature that most people wont need and having a custom event for it would be an extra option.
3. Using MutationObserver would be 2 lines of js, so it won't be a big ugly extra block of DIY code

```js
new MutationObserver(function() {
  console.log(`data-theme is "${document.documentElement.dataset.theme}" now`);
}).observe(document.documentElement, {attributes: true});
```

**Comment by ptfw** [comment]
sound good. thanks. your MutationObserver implementation is shorter than mine! thank you for that! :)

**Comment by souravjamwal77** [comment]
How do we do this in Svelte/Sveltekit for third party chart/graph libraries?

**Comment by saadeghi** [comment]
@souravjamwal77 can you provide an example repo or a Repl with your chart library so I can see what is the problem?

**Comment by souravjamwal77** [comment]
I asked the question out of curiosity and also to know about the setup of theme-change with the other libraries.
I have used D3 but **if you could prefer me to chart/graph libraries that work well with Sveltekit, TailwindCSS, and theme-change**, I can use those libraries. I am learning SvelteKit and would love to explore other libraries that can work with the above stack.
