### ISSUE TITLE
Not working for React

### ISSUE THREAD

**Issue by gunters63** [saadeghi/theme-change#2]
Hi,

I wanted to use this together with DaisyUI in a React application.

Because themeSelect(), themeToggle() and ThemeBtn() all automatically attach to the DOMContentLoaded event it does not work for React out of the box because this event is only fired once after the page is loaded and before React renders.

I worked around the problem by firing the DOMContentLoaded  event manually after my header component with the theme select dropdown rendered the first time, but this is hacky :).

Maybe themeSelect(), themeToggle() and ThemeBtn() can have an optional parameter (bool dontAttach), when this is set it does not attach to DOMContentLoaded so you can call it manually in a useLayoutEffect hook in React or likewise in other client-side frameworks?

**Comment by gunters63** [comment]
I tried this in a [fork](https://github.com/gunters63/theme-change) and it seems to work

**Comment by saadeghi** [comment]
Thanks @gunters63!  
I can merge your fork but I'm looking for a better solution that doesn't require calling DOMContentLoaded event manually.  
I'm keep this issue open for now.

**Comment by gunters63** [comment]
Yeah, its also only a temporary solution for me.
I plan to write a ThemeProvider for React with the same functionality, plus the ability to provide a React Context and a hook (useTheme) because some components I use cannot use CSS variables for theming (charts and 3rd party libs). The hook will provide me with the color values and rerender all connected components whenever the theme changes.

**Comment by gunters63** [comment]
I made a React Component now (ThemeProvider) which internally uses a React Context. Because I need color values in my components (for SVG, Canvas and 3rd party components) I  store my themes now as Javascript objects and set inline styles (with DaisyUi compatible CSS vars) on the fly on my ThemeProvider component.

**Comment by saadeghi** [comment]
@gunters63 That's Cool.  
I'm trying to modify the script somehow to make it work on any environment (Vanilla JS, React, Vue, etc) but I'm still stuck 😅

**Comment by gunters63** [comment]
I can share you my code if you want.
I want the theme data available throughout a React context (color values etc.) so I don't use the supplied DaisyUi themes (made a copy). But probably you can use some ideas.

**Comment by saadeghi** [comment]
Fixed in v2.0.1  

For react projects:
```js
import { useEffect } from 'react';
import {themeChange} from "theme-change"

useEffect(() => {
  themeChange(false)
}, []);
```

I couldn't make it work just with a single `themeChange()` function call so I think using `useEffect` is the only option for now 🤷‍♂️

**Comment by alxvallejo** [comment]
So themeChange(false) ... then what? How do you change a theme from JSX?

**Comment by saadeghi** [comment]
@alxvallejo 
- https://github.com/saadeghi/theme-change#css
- https://github.com/saadeghi/theme-change#html

**Comment by alxvallejo** [comment]
JSX + Remix:

```
// Remix root.tsx:
import tailwindStylesheetUrl from "./styles/tailwind.css";
export const links: LinksFunction = () => {
  return [{ rel: "stylesheet", href: tailwindStylesheetUrl }];
};

...
 
  useEffect(() => {
    themeChange(false);
    const savedTheme = window.localStorage.getItem("theme");
    if (savedTheme) {
      const body = document.body;
      body.setAttribute("data-theme", savedTheme);
    }
  }, []);

  const handleThemeChange = (theme: string) => {
    const body = document.body;
    body.setAttribute("data-theme", theme);
    window.localStorage.setItem("theme", theme);
  };

...

// tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx,jsx,js}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: ["cmyk", "business", "dark", "cyberpunk"],
  },
};

```
