### ISSUE TITLE
Configurable local storage key as optional attribute

### ISSUE THREAD

**Issue by sanskar-mk2** [saadeghi/theme-change#21]
It would be nice to be able to change the key name from `theme` to something else.
It can be something like `<select data-choose-theme data-key="main">`
Now we can either prefix `main` in local storage like `main-theme` or just have `main` as the key.

Thank you.

**Comment by saadeghi** [comment]
What would be the advantages of this feature?

**Comment by sanskar-mk2** [comment]
> What would be the advantages of this feature?

Since local storage is shared by all sites in the domain. If I am lets say using an admin panel package, it will want to set its own theme. Now that would clash with the rest of the site.

So the advantage of this is, allows different themes for different modules of the website.

**Comment by sanskar-mk2** [comment]
Closed by #32
