### ISSUE TITLE
Dark is not applied when the theme changes

### ISSUE THREAD

**Issue by LunaticMuch** [saadeghi/theme-change#25]
I am doing a mockup and this issue might be related to DaisyUI, however, as you can see on this [pen](https://codepen.io/lunaticmuch/pen/PoaPPEB), if you press the top-right button to toggle the dark on/off, the hero banner background does not change.

The definition should make it green in light (or yellow if dark). Whichever starting you point you are, the switch does not trigger the thange 

```
<div class="hero bg-green-400 dark:bg-yellow-400">
```

I am not sure if there's an error in my code. I would expect the change of the theme to pickup the right class prefix if specific.

**Comment by saadeghi** [comment]
Please read this: https://github.com/saadeghi/daisyui/discussions/640#discussioncomment-2424834

And also read daisyUI docs about colors: https://daisyui.com/docs/colors/  
And themes: https://daisyui.com/docs/themes/
