### ISSUE TITLE
Support for DaisyUI Toggle Components (`input type="checkbox"`)

### ISSUE THREAD

**Issue by meunomemauricio** [saadeghi/theme-change#31]
Hi!

Is there any way to make `theme-change` work with [DaisyUI's Toggle components](https://daisyui.com/components/toggle/), without a separate button and JS?

Would be a nice to have, if not.

**Comment by meunomemauricio** [comment]
Sorry! It wasn't working due to another problem. I fixed it and it's working properly now.

Thanks!

**Comment by mikejw** [comment]
@meunomemauricio are you sure this is fixed?  Running into the same issue with version 2.50 and daisyUI 2.51.6

**Comment by mikejw** [comment]
Hi @meunomemauricio how did you get this working?

**Comment by meunomemauricio** [comment]
@mikejw Simply like this:

```javascript
<input type="checkbox" class="toggle" data-toggle-theme="cupcake,dark" />
```

I don't remember the problem I had exactly, but it was in my project's setup. If you can get the demo code working (with buttons, etc), you should also be able do use the checkbox.
