### ISSUE TITLE
null is not an object selectEL.getAttribute 

### ISSUE THREAD

**Issue by Rxbzey** [saadeghi/theme-change#35]
im having this error on my React/Next app working with mac  

![WhatsApp Image 2023-03-02 at 1 39 25 PM](https://user-images.githubusercontent.com/79292224/222584446-289e6e86-721c-4bcc-bfb2-b6c50809656b.jpeg)

then i upgrade to 2.4.0 and this error show up 

![WhatsApp Image 2023-03-02 at 1 58 57 PM](https://user-images.githubusercontent.com/79292224/222585417-1678cb1e-9966-4225-8f56-175acb747314.jpeg)

**Comment by compilekaiten** [comment]
I believe #34 should fix this. Please merge @saadeghi
