### ISSUE TITLE
Remembers theme but forget state after reloading page (React, Next.js)

### ISSUE THREAD

**Issue by ivanskodje** [saadeghi/theme-change#38]
**Problem:**
After refreshing the page, it remembers the current theme but forgot the state.

**Desired solution:**
To somehow get the current theme when loading the page, so I can use it to check which theme button to show (Hopefully without using Redux) :cat2: 

**Code snippet:**
```tsx
import React, { useEffect, useState } from "react";
import { themeChange } from "theme-change";

const ThemeToggleButton = () => {
  const [isDark, setIsDark] = useState(false);

  function toggleTheme() {
    setIsDark(!isDark);
  }

  useEffect(() => {
    themeChange(false);
  }, []);

  return (
    <>
      {isDark ? (
        <button
          onClick={toggleTheme}
          data-set-theme=""
          data-act-class="ACTIVECLASS"
        >
          <span className="material-symbols-outlined text-white">
            light_mode
          </span>
        </button>
      ) : (
        <button
          onClick={toggleTheme}
          data-set-theme="dark"
          data-act-class="ACTIVECLASS"
        >
          <span className="material-symbols-outlined text-white">
            dark_mode
          </span>
        </button>
      )}
    </>
  );
};

export default ThemeToggleButton;

```

**Comment by saadeghi** [comment]
It's not a react component and it doesn't work with React's virtual DOM so we can't expect your state play well with this plugin.  
This plugin directly manipulates DOM (not virtual DOM).  
The way it works, as mentioned [in the docs](https://github.com/saadeghi/theme-change#using-buttons-to-set-a-theme) it adds/removes a class name (`ACTIVECLASS` in the examples)  

You might want to use a React plugin instead if you want to control things using React state.

Let me know if you have any questions.

**Comment by ivanskodje** [comment]
@saadeghi Thank you for your response. When you say "use a React plugin instead", do you mean instead of using theme-change, or did you mean use a React plugin _with_ theme-change as a potential solution to to control the DOM theme? 

Appreciate your response :star:

**Comment by ivanskodje** [comment]
@saadeghi

**Comment by saadeghi** [comment]
Yes, For example https://github.com/pacocoursey/next-themes is similar to this package but it works with virtual DOM which fits better for React if you want to use React hooks.   
`theme-change` works with React regardless of virtual DOM because it directly changes the DOM and doesn't care if it's React or not but if you want to control things using React Hooks I would suggest a React plugin for that (which works with virtual DOM)

**Comment by ivanskodje** [comment]
Thank you very much. After some work I have managed to make `theme-change` work using js-cookie to save and retrieve the state. I will be sharing the `ThemeToggleButton.tsx` which contains all the logic needed to make the theme toggle work with persistence. Just put the button anywhere and it should toggle the theme perfectly between dark and light:

```ts
import React, { useEffect, useLayoutEffect, useState } from "react";
import cookie from "js-cookie";
import { themeChange } from "theme-change";

const ThemeToggleButton = () => {
  const [isDark, setIsDark] = useState(false);

  useLayoutEffect(() => {
    themeChange(false); // Required to always be false for theme-change to work with React
    setIsDark(cookie.get("theme") === "dark");
  }, []);

  function toggleTheme() {
    setIsDark(!isDark);
    cookie.set("theme", isDark ? "light" : "dark");
  }

  return (
    <>
      {isDark ? (
        <button onClick={toggleTheme} data-set-theme="">
          <span className="flex items-center justify-center material-symbols-outlined select-none">
            light_mode
          </span>
        </button>
      ) : (
        <button onClick={toggleTheme} data-set-theme="dark">
          <span className="flex items-center justify-center material-symbols-outlined select-none">
            dark_mode
          </span>
        </button>
      )}
    </>
  );
};

export default ThemeToggleButton;

``` 

In the globals.scss file:

```scss
:root {
  --text-primary: #000000;
  --bg-primary: #ffffff;
  --bg-secondary: #f7f7f7;
}

[data-theme="dark"] {
  --text-primary: #ffffff;
  --bg-primary: #000000;
  --bg-secondary: #1a1a1a;
}
``` 

I am using Next.js, React, Tailwind CSS, and the Material icons.

I hope this can be of help for someone else in the future.
