### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by salihozdemir** [saadeghi/theme-change#4]
Hey there,
This look awesome.

But when i want to use In my typescript project, I need to add @types/theme-change package for types but the package is not available on npm.

**Comment by joanthethings** [comment]
Same problem here

**Comment by saadeghi** [comment]
Does this help?  
https://stackoverflow.com/a/46614891

**Comment by salihozdemir** [comment]
`// @ts-ignore` solved my problem.
