### ISSUE TITLE
Cant integrate with DaisyUI components

### ISSUE THREAD

**Issue by thewh1teagle** [saadeghi/theme-change#46]
It doesn't clear how to integrate with DaisyUI components, 
For instance this component:
https://daisyui.com/components/theme-controller/#theme-controller-using-a-toggle-with-icons

Also i don't see a way set default mode regradless of system mode.

**Comment by saadeghi** [comment]
What is the problem?  
What do you mean "default mode"?

**Comment by thewh1teagle** [comment]
> What is the problem? What do you mean "default mode"?

I used daisyUI Theme Controller, but `theme-change` didn't stored the state of daisyUI theme controller.
```tsx
<label className="flex cursor-pointer gap-2">
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M1 12h2M21 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4"/></svg>
  <input type="checkbox" value="synthwave" className="toggle theme-controller"/>
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>
</label>
```

Default mode:
I would like to set the theme mode to 'light' as the user visit the website in first time,
if he choosed else, `theme-change` will store that and then always use the value stored instead of default one.
Many libraries like that provide the option to select the default mode by `system` or just `light` / `dark`
System means the system dark / light mode (`@media (prefers-dark-interface)`)

**Comment by saadeghi** [comment]
I'm sorry about the misunderstanding. It's not suppose to work.  
`theme-controller` class is a CSS-only solution to change the theme.  
`theme-change` NPM package is a JS package to do the same job using JS so I'm not sure why you're trying to use them together…
If you use `theme-change` NPM package you don't need to `theme-controller` class because it already does the same job using JS.

>Many libraries like that provide the option to select the default mode by system or just light / dark

with `theme-change` NPM package if you give an empty value to `data-theme` it will be system theme.

Let me know if you have a question.

**Comment by thewh1teagle** [comment]
But how do I know the current mode so I can set the design of the slider according to current mode? I don't see any function / value the library expose (react)

**Comment by saadeghi** [comment]
If you're using daisyUI colors, they adapt the current theme so you don't need to do anything.

For example, `bg-base-100` is the background color of current theme (if it's a dark theme, it will be dark background).

To use daisyUI colors for thirdparty plugins, you can do something like this:  
`background: oklch(var(--b1))` for setting the background to daisyUI's `base-100` color.  
The table in this page is the reference for all color variable names: https://daisyui.com/docs/colors/

Let me know if you have a question.

**Comment by thewh1teagle** [comment]
@saadeghi I still need to know the state of the mode for set the slider of DaisyUI as `checked` / or not checked.
![image](https://github.com/saadeghi/theme-change/assets/61390950/08f0ed00-fdcc-45f2-9873-5148466c7550)

**Comment by saadeghi** [comment]
This package `theme-change` doesn't currently support a checkbox input. As mentioned [in the docs](https://github.com/saadeghi/theme-change#html):
There are 3 options:
```html
<button data-set-theme="" data-act-class="ACTIVECLASS"></button>
<button data-set-theme="dark" data-act-class="ACTIVECLASS"></button>
<button data-set-theme="pink" data-act-class="ACTIVECLASS"></button>
```
```html
<button data-toggle-theme="dark,light" data-act-class="ACTIVECLASS"></button>
```
```html
<select data-choose-theme>
  <option value="">Default</option>
  <option value="dark">Dark</option>
  <option value="pink">Pink</option>
</select>
```

I will add support for checkbox input when I get some free time. I'm currently busy with daisyUI tasks.

**Comment by halbano** [comment]
After reading issue, I wanted to bring more light on the currently supported structures for switching the theme, it's also possible to select options using a dropdown with a list within in the following way: 

```
<div className='dropdown'>
      <div tabIndex={0} role='button' className='btn btn-ghost m-1'>
        Switch Theme: {theme}
        <svg
          width='12px'
          height='12px'
          className='h-2 w-2 fill-current opacity-60'
          xmlns='http://www.w3.org/2000/svg'
          viewBox='0 0 2048 2048'
        >
          <path d='M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z'></path>
        </svg>
      </div>
      <ul
        tabIndex={0}
        className='dropdown-content z-[1] p-2 shadow-2xl bg-base-300 rounded-box w-52'
        data-choose-theme
      >
        <li>
          <input
            type='radio'
            name='theme-dropdown'
            className='theme-controller btn btn-sm btn-block btn-ghost justify-start'
            aria-label='System'
            value='default'
            data-set-theme='default'
          />
        </li>
        <li>
          <input
            type='radio'
            name='theme-dropdown'
            className='theme-controller btn btn-sm btn-block btn-ghost justify-start'
            aria-label='Light'
            value='light'
            data-set-theme='light'
          />
        </li>
        <li>
          <input
            type='radio'
            name='theme-dropdown'
            className='theme-controller btn btn-sm btn-block btn-ghost justify-start'
            aria-label='Dark'
            value='dark'
            data-set-theme='dark'
          />
        </li>
      </ul>
    </div>
```
