### ISSUE TITLE
change svg logo color

### ISSUE THREAD

**Issue by woss** [saadeghi/theme-change#48]
Hi, how can use this package together with the changing the SVG logo depending on the theme?

**Comment by saadeghi** [comment]
if it's an inline SVG, you can set the color in CSS for each theme

If it's svg file used as `<img>` tag, you can't control the color using CSS but you can use 2 different `<img>` and then hide them using CSS based on theme.

**Comment by woss** [comment]
i'm afraid i don't get it.

can you please give an example?

also why is not possible to use https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme ?
