### ISSUE TITLE
Error on Next.js

### ISSUE THREAD

**Issue by hrqmonteiro** [saadeghi/theme-change#8]
If i try to use it, i have this error:

![1](https://user-images.githubusercontent.com/17055027/139591531-b246fbc8-8327-42ea-8355-93ad7dbc6da1.png)

Then, on production, it shows it again and don't build:

![2](https://user-images.githubusercontent.com/17055027/139591549-632519cf-44fb-407b-835e-294be1b0ba57.png)

**Comment by saadeghi** [comment]
@hrqmonteiro Are these solutions helpful?  
https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro Are these solutions helpful? https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

No, i actually stumbled upon it and tried it and i got `Client-side Exception Occurred`. My app wouldn't even render.

We need the `@types/theme-change` package in order to avoid this.

**Comment by hrqmonteiro** [comment]
I did the declaration myself, but the button for changing the theme only works in production, when i deploy the app on Vercel, it doesn't work.

You can check it out [here](https://hrqmonteiro.vercel.app)

What could i do to fix it?

**Comment by saadeghi** [comment]
It's working for me 🤔  
video:  

https://user-images.githubusercontent.com/7342023/148054721-fa4956f4-1374-40f0-b512-3e39cce2e475.mp4

**Comment by hrqmonteiro** [comment]
> It's working for me thinking video:
> 1.mp4

Yes, cause i changed it to [next-themes](https://www.npmjs.com/package/next-themes). But this way it only switches between dark and light, i can't use it with the DaisyUI builtin themes (or my custom ones)

I am using the [next-themes](https://github.com/hrqmonteiro/hrqmonteiro.github.io/blob/main/src/components/ui/Menu/index.tsx) on the menu, as you can see here.

But my old button using theme change, see it [here](https://github.com/hrqmonteiro/hrqmonteiro.github.io/blob/192200062b1622d13c3d7eb56471cfa40fa04b36/src/components/ui/ThemesButton/index.tsx) only works in development mode.

**Comment by hrqmonteiro** [comment]
Well, you clearly are not looking to fix this, right?

**Comment by saadeghi** [comment]
You gave me a link, I tried it and it was okay.  
I gave you a video of it working,  
Then you said you're using another package.  
I don't understand how do you expect me to fix an issue when you're not willing to give a repo where I can reproduce the issue? 🤷‍♂️
